name: Performance Test Using K6 for NodeJs

on:
    push:
        branches:
            - main


jobs:
    performance-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up NodeJs Environment
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Install Dependencies
              run: npm install

            - name: Install PM2
              run: npm install -g pm2

            - name: Start Express server with PM2
              run: pm2 start index.js

            - name: Install K6 
              run:  sudo snap install k6

            - name: Run Performance Tests
              run: k6 run ./tests/performance-test.js






